name: ipywebrtc-dev
channels:
  - conda-forge
dependencies:
  - pip
  - nodejs=14.*
  - yarn
  - jupyter-packaging
  - jupyterlab=4
  - notebook
  - ipywidgets>=7.6
  - flake8
  - nbsphinx
  - sphinx
  - sphinx_rtd_theme
  - pygments==2.6.1
  - jupyter-sphinx
